version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  elasticsearch-data:
    driver: local
